# Generated by Django 3.0.7 on 2020-06-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200619_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='group_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='listener',
            name='user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
