# Generated by Django 3.0.7 on 2020-06-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200619_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='chat_type',
            field=models.CharField(choices=[('USER', 'User'), ('ROOM', 'Room'), ('GROUP', 'Group')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listener',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listener',
            name='type',
            field=models.CharField(choices=[('FREEGAME', 'Free Game')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listener',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
