# Generated by Django 3.0.7 on 2020-06-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200619_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='creator_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='listener',
            name='listener_id',
            field=models.CharField(max_length=150),
        ),
    ]
