# Generated by Django 3.0.7 on 2020-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200619_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='game',
            name='provider_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
