# Generated by Django 3.0.7 on 2020-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200619_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='game',
            name='provider_name',
            field=models.CharField(max_length=150),
        ),
    ]
